# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異 ( 100 categories vs 10 categaories )

CIFAR100 is just like the CIFAR-10, except it has 100 classes containing 600 images each. There are 500 training images and 100 testing images per class. The 100 classes in the CIFAR-100 are grouped into 20 superclasses. Each image comes with a "fine" label (the class to which it belongs) and a "coarse" label (the superclass to which it belongs).

In [27]:
import numpy
from keras.datasets import cifar100
import numpy as np
# Set seed number to ensure random number generation deliver the same output.
np.random.seed(100)

# 資料準備

# Image normalize 

# 轉換label 為OneHot Encoding

In [28]:
# Load training and test data
(x_img_train,y_label_train), \
(x_img_test, y_label_test)=cifar100.load_data()

In [29]:
# Print the data count
print('train:',len(x_img_train))
print('test :',len(x_img_test))

train: 50000
test : 10000


In [30]:
# 查詢檔案維度資訊
x_img_train.shape

(50000, 32, 32, 3)

In [31]:
y_label_train.shape

(50000, 1)

In [32]:
# 查詢檔案維度資訊
x_img_test.shape

(10000, 32, 32, 3)

In [33]:
# 查詢檔案維度資訊
y_label_test.shape

(10000, 1)

In [43]:
#針對物件圖像數據集的類別編列成字典
label_dict={
0:"aquatic mammals",
1:"fish",
2:"flowers",
3:"food",
4:"fruit and vegetables",
5:"household electrical devices",
6:"household furniture",
7:"insects",
8:"large carnivores",
9:"large man-made outdoor things",
10:"large natural outdoor scenes",
11:"large omnivores and herbivores",
12:"medium-sized mammals",
13:"non-insect invertebrates",
14:"people",
15:"reptiles",
16:"small mammals",
17:"trees",
18:"vehicles 1",
19:"vehicles 2"
}

In [44]:
#導入影像列印模組
import matplotlib.pyplot as plt

#宣告一個影像標記的函數
def plot_images_labels_prediction(images,labels,prediction,
                                  idx,num=10):
    fig = plt.gcf()
    fig.set_size_inches(12, 14)
    if num>25: num=25 
    for i in range(0, num):
        ax=plt.subplot(5,5, 1+i)
        ax.imshow(images[idx],cmap='binary')
                
        title=str(i)+','+label_dict[labels[i][0]]
        if len(prediction)>0:
            title+='=>'+label_dict[prediction[i]]
            
        ax.set_title(title,fontsize=10) 
        ax.set_xticks([]);ax.set_yticks([])        
        idx+=1 
    plt.show()

In [46]:
#針對不同的影像作標記
#plot_images_labels_prediction(x_img_train,y_label_train,[],0)

In [47]:
print('x_img_test:',x_img_test.shape)
print('y_label_test :',y_label_test.shape)

x_img_test: (10000, 32, 32, 3)
y_label_test : (10000, 1)


In [48]:
x_img_train[0][0][0]

array([255, 255, 255], dtype=uint8)

In [49]:
x_img_train_normalize = x_img_train.astype('float32') / 255.0
x_img_test_normalize = x_img_test.astype('float32') / 255.0

In [50]:
x_img_train_normalize[0][0][0]

array([1., 1., 1.], dtype=float32)

In [51]:
y_label_train.shape

(50000, 1)

In [52]:
y_label_train[:5]

array([[19],
       [29],
       [ 0],
       [11],
       [ 1]])

In [53]:
from keras.utils import np_utils
y_label_train_OneHot = np_utils.to_categorical(y_label_train)
y_label_test_OneHot = np_utils.to_categorical(y_label_test)

In [54]:
y_label_train_OneHot.shape

(50000, 100)

In [55]:
y_label_train_OneHot[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.